version: '3.4'
services:
  k6:
    image: loadimpact/k6:latest
    command: run --insecure-skip-tls-verify /test.js
    deploy:
      mode: replicated
      replicas: 10
    volumes:
      - ./test.js:/test.js
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
