version: '3.1'

services:

  db2:
    image: ibmcom/db2
    privileged: true
    restart: always
    ports:
      - 50001:50000
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: password
      DBNAME: testdb
